import { Router, type IRouter } from "express";
import { ReceiveSendblueWebhookBody, ReceiveSendblueWebhookParams } from "@workspace/api-zod";
import {
  findOrCreateDirectThread,
  findOrCreateGroupThread,
  findOrCreateUser,
  getGroupThreadsForUser,
  getParticipantsNeedingDisclosure,
  hasGroupBeenIntroduced,
  hasOnboardingRecapBeenSent,
  isGroupFullyOnboarded,
  isParticipantMuted,
  loadThreadContext,
  markDisclosureSent,
  markGroupIntroduced,
  markOnboardingRecapSent,
  recordMessage,
  setParticipantMuted,
  setThreadHomeCityIfUnset,
} from "../../lib/agent/context";
import { applyProfileUpdates, runAgentTurn } from "../../lib/agent/engine";
import { scheduleAgentTurn } from "../../lib/agent/debounce";
import { scrubPrivateProfileLeaks } from "../../lib/agent/privacy";
import { sendToThread } from "../../lib/agent/delivery";
import { detectKnowledgeCommand, handleKnowledgeCommand } from "../../lib/agent/knowledge";
import { detectMuteCommand, shouldRespondInGroup } from "../../lib/agent/etiquette";
import {
  clearTiebreak,
  closePollWithWinner,
  computeDatePollWinner,
  countDistinctVoters,
  createPoll,
  getOpenPoll,
  matchOption,
  matchOptions,
  parseTapback,
  recordVote,
  recordVotes,
  tallyPoll,
} from "../../lib/agent/polls";
import {
  confirmBooking,
  detectApprovalIntent,
  draftBooking,
  findPendingBookingForApprover,
  rejectBookingRecord,
} from "../../lib/agent/bookings";
import { confirmPlan, getActivePlan, getOrCreateActivePlan, setPlanScheduledFor, setPlanVenue, setPendingFeedback } from "../../lib/agent/plans";
import { buildGoogleCalendarLink, describePlanSchedule } from "../../lib/agent/calendar";
import { scheduleDayBeforeReminder, scheduleNonVoterNudge } from "../../lib/agent/scheduler";
import { buildReservationLinks, describeReservationLinks } from "../../lib/agent/bookingLinks";
import { buildPlanCardMediaUrl } from "../../lib/agent/planCard";
import { captureOccasion } from "../../lib/agent/occasions";
import { recordPastChoice } from "../../lib/agent/tasteEngine";
import {
  aggregatePrivateInput,
  createPrivateInputRequest,
  getOpenPrivateInputRequestForUser,
  isPrivateInputComplete,
  recordPrivateInputResponse,
  resolvePrivateInputRequest,
} from "../../lib/agent/privateInput";
import { feedbackTable, db, threadParticipantsTable, threadsTable, usersTable } from "@workspace/db";
import { eq } from "drizzle-orm";

/** iMessage tapback text on this poll's own announcement bubbles counts as a vote (Phase 2 texting UX polish). */
const OBJECTION_PATTERN = /\b(no|nope|wait|hold on|object|objection|don'?t lock|actually)\b/i;

const router: IRouter = Router();

/**
 * Runs the main conversation engine for a thread and delivers the result.
 * Invoked from a debounced timer (see `scheduleAgentTurn`) rather than
 * inline in the webhook handler, so a burst of rapid-fire messages collapses
 * into a single agent turn instead of one per message. Because messages are
 * persisted before this runs, the batched turn sees the full burst via its
 * normal transcript load.
 */
async function processAgentTurn(threadId: number, senderUserId: number): Promise<void> {
  const context = await loadThreadContext(threadId);
  const isGroup = context.thread.isGroup;
  const result = await runAgentTurn(context, senderUserId);

  if (result.profileUpdates) {
    await applyProfileUpdates(senderUserId, result.profileUpdates);
  }

  if (result.displayName) {
    await db.update(usersTable).set({ displayName: result.displayName }).where(eq(usersTable.id, senderUserId));
  }

  if (result.onboardingComplete !== null) {
    await db
      .update(usersTable)
      .set({ onboardingStatus: result.onboardingComplete ? "completed" : "in_progress" })
      .where(eq(usersTable.id, senderUserId));

    // Group kickoff recap: once this flips someone to "completed", check
    // whether every group they're in now has a fully-onboarded roster and,
    // if so, send a one-time "everyone's set up" recap for that group. Fires
    // once per group (guarded by `onboardingRecapSentAt`), not once per
    // person who completes.
    if (result.onboardingComplete) {
      const groupThreads = await getGroupThreadsForUser(senderUserId);
      for (const groupThread of groupThreads) {
        if (await hasOnboardingRecapBeenSent(groupThread.id)) continue;
        if (!(await isGroupFullyOnboarded(groupThread.id))) continue;

        const recapContext = await loadThreadContext(groupThread.id);
        const recapLines = recapContext.participants
          .map(({ user, profile }) => {
            // Only ever surface public-visibility fields in a group-bound
            // message -- same rule `scrubPrivateProfileLeaks` enforces for
            // LLM replies, applied explicitly here since this text is
            // assembled directly from profile rows, not generated by the
            // model.
            const bits = [
              profile?.preferencesVisibility === "public" && profile.preferences.length
                ? profile.preferences.join(", ")
                : null,
            ].filter((bit): bit is string => Boolean(bit));
            return `${user.displayName ?? "someone"}${bits.length ? ` (${bits.join("; ")})` : ""}`;
          })
          .join(", ");
        await sendToThread(
          groupThread.id,
          `Everyone's set up now -- here's who I know: ${recapLines}. I'll factor all of that in when I plan things for this group.`,
        );
        await markOnboardingRecapSent(groupThread.id);
      }
    }
  }

  if (result.homeCity) {
    // Best-effort and thread-scoped: apply the learned city to every group
    // this sender is in that doesn't already have one, rather than trying
    // to disambiguate which specific group the mention was about.
    const groupThreads = await getGroupThreadsForUser(senderUserId);
    for (const groupThread of groupThreads) {
      if (!groupThread.homeCity) {
        await setThreadHomeCityIfUnset(groupThread.id, result.homeCity);
      }
    }
  }

  if (result.poll && isGroup) {
    const plan = await getOrCreateActivePlan(threadId, result.poll.question);
    const { poll, options } = await createPoll(threadId, result.poll.question, result.poll.options, {
      kind: result.poll.kind,
      planId: plan.id,
      optionDates: result.poll.optionDates,
    });
    // Tiebreaker persona (and reliable tapback voting) apply to any poll
    // that can stall, not just date polls -- schedule the escalation path
    // for both kinds.
    await scheduleNonVoterNudge(threadId, poll.id);

    // Each option gets its own bubble so a tapback on it is unambiguous
    // (see `parseTapback` -- iMessage quotes the whole reacted message).
    for (const [index, option] of options.entries()) {
      await sendToThread(threadId, `${index + 1}. ${option.label}`);
    }
  }

  if (result.occasion) {
    const aboutUser = result.occasion.aboutName
      ? context.participants.find(
          (p) => p.user.displayName?.toLowerCase() === result.occasion?.aboutName?.toLowerCase(),
        )?.user
      : undefined;
    await captureOccasion({
      threadId,
      aboutUserId: aboutUser?.id ?? null,
      mentionedByUserId: senderUserId,
      kind: result.occasion.kind,
      label: result.occasion.label,
      occasionDate: result.occasion.date,
    });
  }

  if (result.privateQuestion && isGroup) {
    const plan = await getActivePlan(threadId);
    const request = await createPrivateInputRequest(threadId, plan?.id ?? null, result.privateQuestion);
    for (const { user } of context.participants) {
      if (!user.phoneNumber) continue;
      const { thread: dmThread } = await findOrCreateDirectThread(user.phoneNumber);
      await sendToThread(dmThread.id, result.privateQuestion);
    }
    // Track which request each DM thread is currently answering isn't
    // needed explicitly -- `getOpenPrivateInputRequestForUser` resolves it
    // by joining through thread_participants, since a request is keyed to
    // the group thread and every participant is a member of it.
    void request;
  }

  if (result.bookingDraft) {
    const approverPhone = result.bookingDraft.approverPhoneNumber;
    const approver = approverPhone ? await findOrCreateUser(approverPhone) : { id: senderUserId };
    const plan = await getOrCreateActivePlan(threadId, result.bookingDraft.title);
    const booking = await draftBooking({
      threadId,
      planId: plan.id,
      createdByUserId: senderUserId,
      approverUserId: approver.id,
      title: result.bookingDraft.title,
      details: result.bookingDraft.details,
    });

    if (approver.id !== senderUserId) {
      const { thread: approverThread } = await findOrCreateDirectThread(approverPhone as string);
      await sendToThread(
        approverThread.id,
        `Heads up -- can you approve this booking: "${booking.title}"? Reply YES to confirm or NO to skip it.`,
      );
    }
  }

  // Preference privacy enforcement: private profile fields may have silently
  // shaped this reply, but they must never surface verbatim in group-visible
  // text. 1:1 threads skip this -- there's nothing to leak the info to.
  const outgoingReply = isGroup ? scrubPrivateProfileLeaks(result.reply, context.participants) : result.reply;

  await sendToThread(threadId, outgoingReply);
}

router.post("/webhooks/sendblue/:secret", async (req, res): Promise<void> => {
  const params = ReceiveSendblueWebhookParams.safeParse(req.params);
  const expectedSecret = process.env["SENDBLUE_WEBHOOK_SECRET"];

  // Sendblue does not sign webhook payloads, so the shared secret embedded in
  // the URL we register with them is the only authenticity check available.
  // Reject silently (no 200 ack) rather than processing unauthenticated
  // events -- an attacker with the wrong secret should not be able to inject
  // messages, cast votes, or approve/reject bookings.
  if (!expectedSecret) {
    req.log.error("SENDBLUE_WEBHOOK_SECRET is not configured; rejecting webhook request");
    res.status(503).json({ error: "Webhook not configured" });
    return;
  }
  if (!params.success || params.data.secret !== expectedSecret) {
    req.log.warn("Rejected Sendblue webhook request with invalid secret");
    res.status(401).json({ error: "Unauthorized" });
    return;
  }

  const parsed = ReceiveSendblueWebhookBody.safeParse(req.body);
  if (!parsed.success) {
    req.log.warn({ errors: parsed.error.message }, "Invalid Sendblue webhook payload");
    res.status(200).json({ received: true });
    return;
  }

  const event = parsed.data;

  // Ignore delivery-status callbacks for our own outbound sends, and anything
  // without message content -- we only react to actual inbound text.
  if (event.is_outbound || !event.content || !event.from_number) {
    res.status(200).json({ received: true });
    return;
  }

  try {
    const isGroup = Boolean(event.group_id);

    let threadId: number;
    let senderUserId: number;

    if (isGroup && event.group_id) {
      const groupId = event.group_id;
      const participantNumbers = event.participants?.length ? event.participants : [event.from_number];
      const { thread, participants } = await findOrCreateGroupThread(groupId, participantNumbers);
      threadId = thread.id;
      const sender = participants.find((p) => p.phoneNumber === event.from_number) ?? (await findOrCreateUser(event.from_number));
      senderUserId = sender.id;

      // One-time, whole-group intro when the concierge is first added to a
      // new group -- said once, ever, regardless of how many people later
      // join. Distinct from the per-person welcome below.
      if (!(await hasGroupBeenIntroduced(threadId))) {
        await sendToThread(
          threadId,
          `Hi all -- I'm this group's AI concierge. I help plan things here (polls, bookings, reminders). Say "what do you know about me?" any time to see what I've learned, or "mute you" to have me stay quiet.`,
        );
        await markGroupIntroduced(threadId);
      }

      // Any participant the concierge doesn't have a profile for yet gets a
      // short one-line welcome in the group -- never a full questionnaire
      // dropped into the group -- plus an optional 1:1 DM where the actual
      // preference-gathering questions happen privately.
      const needingDisclosure = await getParticipantsNeedingDisclosure(threadId);
      for (const person of needingDisclosure) {
        // Cross-thread memory: someone who already has a completed profile
        // from another thread is a known quantity the moment they show up
        // here -- skip re-running the preference questionnaire and just
        // acknowledge that the concierge already knows them.
        const isReturningMember = person.onboardingStatus === "completed";
        await sendToThread(
          threadId,
          isReturningMember
            ? `Hey ${person.displayName ?? "there"}, welcome -- I already know your usual picks, so I'll factor those in.`
            : `Hey ${person.displayName ?? "there"}, welcome -- glad to have you here.`,
        );
        await markDisclosureSent(threadId, person.id);

        if (!isReturningMember && person.phoneNumber) {
          const { thread: dmThread } = await findOrCreateDirectThread(person.phoneNumber);
          await sendToThread(
            dmThread.id,
            `Hi! I'm the AI concierge for that group -- I help plan the dinners, hangouts, and "where should we all meet" of it all. Two things whenever you've got a sec: what's your go-to order when you don't want to think about it, and any budget range or dietary needs I should keep in mind? Totally optional, just reply here whenever.`,
          );
        }
      }
    } else {
      const { thread, user } = await findOrCreateDirectThread(event.from_number);
      threadId = thread.id;
      senderUserId = user.id;
    }

    await recordMessage({
      threadId,
      userId: senderUserId,
      direction: "inbound",
      role: "user",
      content: event.content,
      sendblueMessageHandle: event.message_handle ?? null,
      rawPayload: event,
    });

    // 1. Deterministic commands that must always work regardless of mute
    // state or LLM behavior: mute/unmute and "what do you know about me".
    const muteCommand = detectMuteCommand(event.content);
    if (muteCommand) {
      await setParticipantMuted(threadId, senderUserId, muteCommand === "mute");
      await sendToThread(
        threadId,
        muteCommand === "mute" ? "Got it, I'll stay quiet in here until you unmute me." : "I'm back -- happy to help again.",
      );
      res.status(200).json({ received: true });
      return;
    }

    const knowledgeCommand = detectKnowledgeCommand(event.content);
    if (knowledgeCommand) {
      const reply = await handleKnowledgeCommand(senderUserId, knowledgeCommand);
      await sendToThread(threadId, reply);
      res.status(200).json({ received: true });
      return;
    }

    // 2. A pending post-plan feedback prompt takes priority over everything
    // else conversational -- if we just asked "how was it?", this reply is
    // almost certainly the answer.
    const [threadRow] = await db.select().from(threadsTable).where(eq(threadsTable.id, threadId));
    if (threadRow?.pendingFeedbackPlanId) {
      const ratingMatch = event.content.trim().match(/^([1-5])\b/);
      const value = ratingMatch
        ? { rating: Number.parseInt(ratingMatch[1] as string, 10) }
        : { text: event.content.trim() };
      await db.insert(feedbackTable).values({
        threadId,
        planId: threadRow.pendingFeedbackPlanId,
        userId: senderUserId,
        kind: ratingMatch ? "rating" : "free_text",
        value,
      });
      await setPendingFeedback(threadId, null);
      await sendToThread(threadId, "Thanks for the feedback -- noted for next time!");
      res.status(200).json({ received: true });
      return;
    }

    // 2.5. Private aggregation over DM: if this is a 1:1 thread and the
    // sender owes an answer to an open private-input request, this reply is
    // almost certainly that answer, not a normal chat message. Only the
    // combined result (never this raw answer) ever reaches the group.
    if (!isGroup) {
      const openRequest = await getOpenPrivateInputRequestForUser(senderUserId);
      if (openRequest) {
        await recordPrivateInputResponse(openRequest.id, senderUserId, event.content);
        await sendToThread(threadId, "Got it, thanks -- keeping that between us.");

        if (await isPrivateInputComplete(openRequest)) {
          const summary = await aggregatePrivateInput(openRequest);
          await resolvePrivateInputRequest(openRequest.id, summary);
          await sendToThread(openRequest.threadId, summary);
        }

        res.status(200).json({ received: true });
        return;
      }
    }

    // 3. If there's an open poll on this thread, check whether this message is a vote.
    const openPoll = await getOpenPoll(threadId);
    if (openPoll) {
      // Tiebreaker persona: if an "executive decision" is currently in its
      // objection window, a deterministic objection cancels the auto-lock
      // rather than being treated as a vote or a normal chat message.
      if (openPoll.poll.tiebreakAnnouncedAt && OBJECTION_PATTERN.test(event.content)) {
        await clearTiebreak(openPoll.poll.id);
        await sendToThread(threadId, "Got it, holding off -- what would you prefer instead?");
        res.status(200).json({ received: true });
        return;
      }

      // Texting UX polish: an iMessage tapback ("Loved \"...\"") on one of
      // the poll's own option bubbles counts as a vote for that option.
      // Only positive reactions (loved/liked/emphasized) register.
      const tapback = parseTapback(event.content);
      const effectiveContent = tapback && tapback.isPositive ? tapback.quotedContent : event.content;
      if (tapback && !tapback.isPositive) {
        res.status(200).json({ received: true });
        return;
      }

      if (openPoll.poll.kind === "date") {
        const matched = matchOptions(effectiveContent, openPoll.options);
        if (matched.length > 0) {
          await recordVotes(openPoll.poll.id, matched.map((m) => m.id), senderUserId);
          const participantRows = await db
            .select()
            .from(threadParticipantsTable)
            .where(eq(threadParticipantsTable.threadId, threadId));
          // isFullIntersection is judged against the whole thread's expected
          // participant count, not just current voters -- otherwise the
          // very first vote would trivially "intersect with itself" and
          // close the poll before anyone else weighs in.
          const winner = await computeDatePollWinner(openPoll.poll.id, openPoll.options, participantRows.length);
          const voterCount = await countDistinctVoters(openPoll.poll.id);

          if (winner && (winner.isFullIntersection || voterCount >= participantRows.length)) {
            await closePollWithWinner(openPoll.poll.id, winner.option.id);
            if (openPoll.poll.planId) {
              const winningOption = openPoll.options.find((o) => o.id === winner.option.id);
              if (winningOption?.optionDate) {
                await setPlanScheduledFor(openPoll.poll.planId, winningOption.optionDate);
              }
            }
            await sendToThread(
              threadId,
              winner.isFullIntersection
                ? `Everyone's free "${winner.option.label}" -- let's lock that in.`
                : `We didn't get a date that works for literally everyone, so going with the best overlap: "${winner.option.label}".`,
            );
          } else {
            await sendToThread(
              threadId,
              `Got it -- noted (${voterCount}/${participantRows.length} have responded so far).`,
            );
          }
          res.status(200).json({ received: true });
          return;
        }
      } else {
        const matched = matchOption(effectiveContent, openPoll.options);
        if (matched) {
          await recordVote(openPoll.poll.id, matched.id, senderUserId);
          const tally = await tallyPoll(openPoll.poll.id, openPoll.options);
          const voterCount = await countDistinctVoters(openPoll.poll.id);
          const participantRows = await db
            .select()
            .from(threadParticipantsTable)
            .where(eq(threadParticipantsTable.threadId, threadId));

          const tallyLine = tally.map((t) => `${t.option.label}: ${t.voteCount}`).join(", ");

          if (voterCount >= participantRows.length) {
            const winnerTally = [...tally].sort((a, b) => b.voteCount - a.voteCount)[0];
            if (winnerTally) {
              await closePollWithWinner(openPoll.poll.id, winnerTally.option.id);
              if (openPoll.poll.planId) {
                await setPlanVenue(openPoll.poll.planId, winnerTally.option.label);
              }
              await sendToThread(
                threadId,
                `Everyone's voted! We're going with "${winnerTally.option.label}" (${tallyLine}).`,
              );
            }
          } else {
            await sendToThread(
              threadId,
              `Got it. Current tally (${voterCount}/${participantRows.length} voted) -- ${tallyLine}`,
            );
          }

          res.status(200).json({ received: true });
          return;
        }
      }
    }

    // 4. If this sender is the designated approver for a pending booking, check for an approval/rejection.
    const pendingBooking = await findPendingBookingForApprover(senderUserId);
    if (pendingBooking) {
      const intent = detectApprovalIntent(event.content);
      if (intent === "approve") {
        const booking = await confirmBooking(pendingBooking.id);
        let confirmationSuffix = "";
        let mediaUrl: string | undefined;
        if (booking.planId) {
          const plan = await confirmPlan(booking.planId);
          const link = buildGoogleCalendarLink(plan);
          confirmationSuffix = ` ${describePlanSchedule(plan)}.${link ? ` Add it to your calendar: ${link}` : ""}`;
          if (plan.scheduledFor) {
            await scheduleDayBeforeReminder(booking.threadId, plan.id, plan.scheduledFor);
          }

          // Plan cards: a visual confirmation card once the plan is locked in.
          const attendeeRows = await db
            .select({ user: usersTable })
            .from(threadParticipantsTable)
            .innerJoin(usersTable, eq(threadParticipantsTable.userId, usersTable.id))
            .where(eq(threadParticipantsTable.threadId, booking.threadId));
          const attendeeNames = attendeeRows.map((row) => row.user.displayName ?? row.user.phoneNumber);
          mediaUrl = (await buildPlanCardMediaUrl(plan, attendeeNames)) ?? undefined;

          // Cross-thread memory: remember what this group actually did, per
          // person, so the next thread this person is in (even a brand new
          // group) already has real history to draw on -- not just stated
          // preferences.
          if (plan.venue) {
            await Promise.all(attendeeRows.map((row) => recordPastChoice(row.user.id, plan.venue as string)));
          }
        }

        // Booking deep links: a pre-filled Resy/OpenTable search, framed
        // explicitly as a search, never a guaranteed table.
        const links = buildReservationLinks(booking);
        const linksLine = ` ${describeReservationLinks(links)}`;

        await sendToThread(booking.threadId, `Confirmed: "${booking.title}".${confirmationSuffix}${linksLine}`, mediaUrl);
        if (booking.threadId !== threadId) {
          await sendToThread(threadId, `Thanks -- approved "${booking.title}".`);
        }
        res.status(200).json({ received: true });
        return;
      }
      if (intent === "reject") {
        const booking = await rejectBookingRecord(pendingBooking.id);
        await sendToThread(
          booking.threadId,
          `No problem, I've dropped "${booking.title}". Let me know if you want to plan something else.`,
        );
        if (booking.threadId !== threadId) {
          await sendToThread(threadId, `Got it -- rejected "${booking.title}".`);
        }
        res.status(200).json({ received: true });
        return;
      }
    }

    // 5. Group-chat etiquette: stay silent if this thread is muted for this
    // person, or if the message isn't addressed to the concierge and has no
    // clear planning intent -- a busy group shouldn't get a reply to every
    // message just because the concierge is present.
    if (isGroup) {
      if (await isParticipantMuted(threadId, senderUserId)) {
        res.status(200).json({ received: true });
        return;
      }
      if (!shouldRespondInGroup(event.content)) {
        res.status(200).json({ received: true });
        return;
      }
    }

    // 6. Otherwise, hand off to the (debounced) main conversation engine and
    // ack immediately -- the reply is delivered asynchronously once the
    // debounce window closes, so a burst of messages only triggers one turn.
    scheduleAgentTurn(threadId, senderUserId, event.content, processAgentTurn);

    res.status(200).json({ received: true });
  } catch (error) {
    req.log.error({ error }, "Failed to process Sendblue webhook event");
    // Always ack the webhook so Sendblue doesn't retry indefinitely.
    res.status(200).json({ received: true });
  }
});

export default router;
